---
name: App-ZofCMS-Plugin-RandomBashOrgQuote
version: 0.0101
author:
  - "'Zoffix <'zoffix@cpan.org'>"
abstract: tiny plugin to fetch random quotes from http://bash.org/
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  WWW::BashOrg: 0.0101
build_requires:
  Test::More: 0
provides:
  App::ZofCMS::Plugin::RandomBashOrgQuote:
    file: lib/App/ZofCMS/Plugin/RandomBashOrgQuote.pm
    version: 0.0101
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
